/**
 * Generate `.github/workflows/wake.yml` from local `.env`.
 *
 * Only maps secrets that are set locally — missing keys are omitted
 * (empty `${{ secrets.X }}` refs are harmless but noisy).
 *
 * Usage: npm run generate:wake-workflow
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { config as loadDotenv } from "dotenv";

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const workflowPath = path.join(rootDir, ".github", "workflows", "wake.yml");
const defaultCron = "0 0 * * *";

/**
 * Env vars the wake job may need. `secretName` is the GitHub Actions secret
 * (defaults to the env key). Skip vars that are unset / blank in `.env`.
 */
const WAKE_ENV_KEYS: Array<{
  env: string;
  /** GitHub secret name when it must differ from the process env key. */
  secretName?: string;
  /** Omit from Actions (HTTP trigger only). */
  skip?: boolean;
}> = [
  // Built-in Actions GITHUB_TOKEN collides — store as ROOSTER_GITHUB_TOKEN.
  { env: "GITHUB_TOKEN", secretName: "ROOSTER_GITHUB_TOKEN" },
  { env: "CALENDAR_ICS_URL" },
  { env: "IMAP_HOST" },
  { env: "IMAP_PORT" },
  { env: "IMAP_USER" },
  { env: "IMAP_PASS" },
  { env: "OPENAI_API_KEY" },
  { env: "OPENAI_BASE_URL" },
  { env: "GEMINI_API_KEY" },
  { env: "TELEGRAM_BOT_TOKEN" },
  { env: "TELEGRAM_CHAT_ID" },
  { env: "ANTHROPIC_API_KEY" },
  { env: "GA4_PROPERTY_ID" },
  // File path locally → JSON blob secret + write step (handled separately).
  { env: "GOOGLE_APPLICATION_CREDENTIALS", skip: true },
  { env: "ROOSTER_RUN_TOKEN", skip: true },
];

function envIsSet(name: string, env: NodeJS.ProcessEnv): boolean {
  const value = env[name];
  return value !== undefined && value.trim() !== "";
}

function readExistingCron(filePath: string): string | null {
  if (!existsSync(filePath)) {
    return null;
  }
  const raw = readFileSync(filePath, "utf8");
  const match = /cron:\s*"([^"]+)"/.exec(raw);
  return match?.[1] ?? null;
}

function yamlQuote(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function buildWorkflow(options: {
  cron: string;
  envLines: string[];
  includeGa4Credentials: boolean;
}): string {
  const envBlock =
    options.envLines.length > 0
      ? ["        env:", ...options.envLines.map((line) => `          ${line}`)].join(
          "\n",
        )
      : "        # No secrets detected in .env — wake will use stub LLM / defaults.\n        # Re-run after filling keys, then add matching repo secrets.";

  const ga4Step = options.includeGa4Credentials
    ? `
      - name: Write GA4 service account
        env:
          GA4_SERVICE_ACCOUNT_JSON: \${{ secrets.GA4_SERVICE_ACCOUNT_JSON }}
        run: |
          if [ -z "$GA4_SERVICE_ACCOUNT_JSON" ]; then
            echo "GA4_SERVICE_ACCOUNT_JSON secret is missing — add the service-account JSON in repo Settings → Secrets."
            exit 1
          fi
          printf '%s\\n' "$GA4_SERVICE_ACCOUNT_JSON" > ga4-service-account.json
`
    : "";

  return `# Generated by \`npm run generate:wake-workflow\` from local .env.
# Edit the cron expression below; re-run the script to refresh env mappings.
# Docs: docs/SCHEDULING.md
#
# After generating:
# 1. Add the listed secrets under repo Settings → Secrets and variables → Actions
# 2. Commit this file (and optionally a non-secret rooster.config.json)
# 3. Actions → Wake the Flock Up → Run workflow (or wait for schedule)

name: Wake the Flock Up

on:
  schedule:
    - cron: ${yamlQuote(options.cron)} # UTC — match rooster.config.json timezone
  workflow_dispatch:

jobs:
  wake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: npm

      - run: npm ci

      - name: Write rooster.config.json (optional)
        env:
          ROOSTER_CONFIG_JSON: \${{ secrets.ROOSTER_CONFIG_JSON }}
        run: |
          if [ -n "$ROOSTER_CONFIG_JSON" ]; then
            printf '%s\\n' "$ROOSTER_CONFIG_JSON" > rooster.config.json
          elif [ -f rooster.config.json ]; then
            echo "Using committed rooster.config.json"
          else
            echo "No rooster.config.json — wake will use env defaults (see docs/SCHEDULING.md)"
          fi
${ga4Step}
      - name: Wake the Flock Up
        run: npm run wake
${envBlock}
`;
}

function main(): void {
  loadDotenv({ path: path.join(rootDir, ".env"), quiet: true });

  const cron = readExistingCron(workflowPath) ?? defaultCron;
  const envLines: string[] = [];
  const secretsToAdd: string[] = [];

  // Skip companion vars when the credential that needs them is missing
  // (e.g. OPENAI_BASE_URL alone, or IMAP_HOST without IMAP_PASS).
  const skipCompanions = new Set<string>();
  if (!envIsSet("OPENAI_API_KEY", process.env)) {
    skipCompanions.add("OPENAI_BASE_URL");
  }
  if (!envIsSet("IMAP_PASS", process.env) && !envIsSet("IMAP_USER", process.env)) {
    skipCompanions.add("IMAP_HOST");
    skipCompanions.add("IMAP_PORT");
  }

  for (const entry of WAKE_ENV_KEYS) {
    if (entry.skip || skipCompanions.has(entry.env)) {
      continue;
    }
    if (!envIsSet(entry.env, process.env)) {
      continue;
    }
    const secretName = entry.secretName ?? entry.env;
    // Process env key on the left; GitHub secret on the right.
    envLines.push(`${entry.env}: \${{ secrets.${secretName} }}`);
    secretsToAdd.push(
      entry.secretName
        ? `${secretName}  (maps to ${entry.env} — do not use the built-in GITHUB_TOKEN)`
        : secretName,
    );
  }

  const includeGa4 = envIsSet("GOOGLE_APPLICATION_CREDENTIALS", process.env);
  if (includeGa4) {
    envLines.push(
      "GOOGLE_APPLICATION_CREDENTIALS: ./ga4-service-account.json",
    );
    secretsToAdd.push(
      "GA4_SERVICE_ACCOUNT_JSON  (full service-account JSON file contents)",
    );
  }

  // Optional config blob — always documented, step always present.
  secretsToAdd.push(
    "ROOSTER_CONFIG_JSON  (optional — paste rooster.config.json if it is not committed)",
  );

  const yaml = buildWorkflow({ cron, envLines, includeGa4Credentials: includeGa4 });
  mkdirSync(path.dirname(workflowPath), { recursive: true });
  writeFileSync(workflowPath, yaml, "utf8");

  console.log(`Wrote ${path.relative(rootDir, workflowPath)}`);
  console.log(`Cron: ${cron} (UTC)`);
  if (envLines.length === 0 && !includeGa4) {
    console.log("No wake secrets found in .env — workflow has no env block yet.");
  } else {
    console.log(`Mapped ${envLines.length} env line(s) from .env.`);
  }
  console.log("");
  console.log("Add these repository secrets (Settings → Secrets and variables → Actions):");
  for (const name of secretsToAdd) {
    console.log(`  - ${name}`);
  }
  console.log("");
  console.log("Then commit .github/workflows/wake.yml and push.");
}

main();
